### ISSUE TITLE
Support .sav files

### ISSUE THREAD

**Issue by dolgarev** [izhaks/PK01LvovEmulator#1]
Hello!
Can you add support .sav dumps?

**Comment by izhaks** [comment]
> Hello!
> Can you add support .sav dumps?

Hi!
This is not currently planned.
What are .sav dumps? How are they different from the .lvd dumps (supported by this emulator)?

**Comment by dolgarev** [comment]
@izhaks We don't have any soft in .lvd format. This is an archaeological artifact. :)))
The archive of programs is available in .lvt and .sav format. You can read about the latter on the forum. I see it - "[Форматы файлов ПК-01 "Львов" для эмуляторов](http://pc01.lviv.ua/forum/viewtopic.php?f=12&t=102)".

**Comment by izhaks** [comment]
> @izhaks We don't have any soft in .lvd format. This is an archaeological artifact. :)))
> The archive of programs is available in .lvt and .sav format. You can read about the latter on the forum. I see it - "[Форматы файлов ПК-01 "Львов" для эмуляторов](http://pc01.lviv.ua/forum/viewtopic.php?f=12&t=102)".

Intresting... There is little information, but they say there that:
"Если хедер начинается с "LVOV/DUMP/2.0/" - то это *.sav файл (дамп эмуля Калашникова)."
This emulator is based on Vladimir Kalashnikov's emulator, and .lvd dump files start with:
"LVOV/DUMP/3.0/"
So there is probably a very small difference, but what?..

**Comment by dolgarev** [comment]
I found [some info](http://web1.fdd5-25.net/~lvovpk/ftp/lvov20j1/emul.htm) -
>  DUMP .SAV
--
Формат дампов старой версии эмулятора 1.xне поддерживается, во многом в свое время он предназначался для отладки, не рекомендую его использовать для распространения ПО, следует обратить внимание на формат .RSS В.Пыхонина


But we have the fact that .sav survived and won in a historical perspective.

**Comment by izhaks** [comment]
@dolgarev Hi!
I have just implemented loading and saving of .SAV dump files.
Thank you for your help!
